### ISSUE TITLE
[2] No confirmation message when maze is loaded

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#29]
#26 TC01 - Maze is loaded but no confirmation message displayed to indicate it has been loaded properly.

**Comment by halfofning** [comment]
No explicit confirmation message is needed for this feature.

When a user enters a maze .csv file that exists, the confirmation part will be the "Number of lines..." message. Otherwise, another message will be displayed depending on what the error is.

<img width="283" alt="Screenshot 2020-02-05 at 11 54 35 PM" src="https://user-images.githubusercontent.com/28654855/73858131-dda0dc80-4872-11ea-96fb-e0ae4253b85e.png">

A **valid** maze file will show something like this when option 2 is selected.

<img width="279" alt="Screenshot 2020-02-05 at 11 54 57 PM" src="https://user-images.githubusercontent.com/28654855/73858166-eb566200-4872-11ea-9799-ea433331e510.png">

An **invalid** maze file will show this when option 2 is selected.

<img width="360" alt="Screenshot 2020-02-05 at 11 57 40 PM" src="https://user-images.githubusercontent.com/28654855/73858404-4d16cc00-4873-11ea-9e21-bb14e40ac9aa.png">

Thanks! 🤟🏻

**Comment by janinedesiree** [comment]
@halfofning Noted on the expected behaviour for this. Thanks for the clarification!
